version: "3.8"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - java_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db_spring

  spring-jwt:
    container_name: spring-jwt
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    networks:
      - java_network
    depends_on:
      - postgres
    restart: on-failure
    environment:
      - POSTGRESQL_HOST=postgres_container
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=root
networks:
  java_network:
    name: java_network
